### ISSUE TITLE
Implement Google Analytics

### ISSUE THREAD

**Issue by sinproject-iwasaki** [sinProject-Inc/back-to-domain#17]
# Tasks

参考：https://github.com/sinProject-Inc/sinpro-dev/pull/232/files

- [x] [Create a Google Analytics Account](https://analytics.google.com/analytics/web/#/a282908538p414545330/admin)
- [x] Add gtag

Estimated Time: 20min

# Writing the Issue

- [x] Write each task for this issue using checkboxes
- [x] Write all verbal instructions as tasks
- [x] Add labels and assignees

# Before Working on the Issue

- [x] Assign yourself
- [x] Git: Fetch the latest main
- [x] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [x] Insure that changes include only what is necessary for this PR
- [x] Implement necessary Unit tests
- [x] Implement necessary E2E tests
- [x] Perform functionality checks
