### ISSUE TITLE
Configure repository

### ISSUE THREAD

**Issue by sinproject-iwasaki** [sinProject-Inc/back-to-domain#3]
# Tasks

## Update template-for-sveltekit!!!

- [x] update `create_git_branch.ts`
- [x] update `pre-commit`
- [x] update `sonar.coverage.exclusions`

## npm

- [x] `npm i`
- [x] `ncu`
- [x] `ncu -u`
- [x] `npm i`

## run

- [x] `npm run dev`

## actions

- [x] update `ci.yml`

## template

- [x] update `release.md`

## husky

- [x] sh `.husky/pre-commit`

## pm2

- [x] update `ecosystem.config.cjs`

## readme

- [x] update `readme.md`

## code climate

- [x] add repository

## sonarcloud

- [x] add repository
- [x] update `sonar-project.porperties`

## github

- [x] activate CodeQL analysis
- [x] protect main branch

## tests

- [x] `npm run test:unit`
- [x] `npx playwright install`
- [x] `npm run test:integration`

Estimated Time: 120min

# Writing the Issue

- [x] Write each task for this issue using checkboxes
- [x] Write all verbal instructions as tasks
- [x] Add labels and assignees

# Before Working on the Issue

- [x] Assign yourself
- [x] Share your screen on Discord
- [x] Write which issue you are starting on Slack
- [x] Git: Fetch the latest main
- [x] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [x] Insure that changes include only what is necessary for this PR
- [x] Implement necessary Unit tests
- [x] Implement necessary E2E tests
- [x] Perform functionality checks
