### ISSUE TITLE
Setup server for first release

### ISSUE THREAD

**Issue by sinproject-iwasaki** [sinProject-Inc/back-to-domain#31]
# Tasks

## DNS

- [x] Open [DNS settings](https://domains.google.com/registrar/sinpro.dev/dns?_ga=2.199337390.140363374.1699246074-1292223345.1699246074&_gl=1*u6okjs*_gcl_au*MjA5OTQwNjE4OS4xNjk5MjQ2MDc2*_ga*MTI5MjIyMzM0NS4xNjk5MjQ2MDc0*_ga_9YWT2H669H*MTY5OTI0NjA3NS4xLjAuMTY5OTI0NjA3NS4wLjAuMA..)
- [x] Add a new custom record back-to-domain A 3600 153.127.46.103

## Repository

- [x] `ssh dev@sinpro-dev` で接続する。
- [x] `git clone https://github.com/sinProject-Inc/back-to-domain.git`
- [x] `sudo micro /etc/caddy/CaddyfiAle`
- [x] git checkout main && git pull
- [x] npm i
- [x] npm run build
- [x] pm2 start ecosystem.config.cjs

## Caddy

- [x] Updare caddyfile
- [x] `sudo systemctl restart caddy`

## Tests

- [ ] Vitest https://back-to-domain.sinpro.dev

## Documents

- [ ] write a document on sinpro.dev

Estimated Time: XXmin

# Writing the Issue

- [x] Write each task for this issue using checkboxes
- [x] Write all verbal instructions as tasks
- [x] Add labels and assignees

# Before Working on the Issue

- [x] Assign yourself
- [ ] Git: Fetch the latest main
- [ ] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [ ] Insure that changes include only what is necessary for this PR
- [ ] Implement necessary Unit tests
- [ ] Implement necessary E2E tests
- [ ] Perform functionality checks
